name: Full Stack CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Backend CI
      - name: Install Backend Dependencies
        working-directory: ./
        run: npm install

      # Frontend CI
      - name: Install Frontend Dependencies
        working-directory: ./client
        run: npm install --force

      - name: Run Frontend Linting
        working-directory: ./client
        run: npm run lint

      - name: Build Frontend
        working-directory: ./client
        run: npm run build --prod
